# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'islamico' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for islamico
  pod 'Fabric'
  pod 'Crashlytics'
  target 'islamicoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
