module.exports = {
    APIHelperRequestTypeMasjid: '/api/v2/masjid/',
    APIHelperRequestTypeSingleContent: '/api/v2/content/',
    APIHelperRequestTypeMasjidLite: '/api/v1/masjid?lite=true',
    APIHelperRequestTypeContentFeed: '/api/v2/feed',
    APIHelperRequestTypeContentEvent: '/api/v1/event',
    APIHelperRequestTypeContentNews: '/api/v1/news',
    APIHelperRequestTypeContentVideo: '/api/v1/video',
    APIHelperRequestTypeUserEventParticipant: '/api/v1/me/participant/',
    APIHelperRequestTypeUserEventVolunteer: '/api/v1/me/volunteer/',
    APIHelperRequestTypeUserEmailChecker: '/api/v1/emailChecker',
    APIHelperRequestTypeAuthenticate: '/api/v1/authenticate',
    APIHelperRequestTypeContentProgram: '/api/v1/program',
    APIHelperRequestTypeContentProject: '/api/v1/project',
    APIHelperRequestTypeEventRemoveParticipantRegistration: '/api/v1/event/registration/cancel',
    APIHelperRequestTypeEventRemoveVolunteerRegistration: '/api/v1/event/volunteer/cancel',
    APIHelperRequestTypeTransactionRequestToken: '/api/v1/payment/tokenRequest',
    APIHelperRequestTypeUserRegister: '/api/v1/register',
    APIHelperRequestTypeUserUpdateProfile: '/api/v1/me',
    APIHelperRequestTypeEventParticipantRegistration: '/api/v1/event/registration',
    APIHelperRequestTypeEventVolunteerRegistration: '/api/v1/event/volunteer',
    APIHelperRequestTypePaymentRequest: '/api/v2/paymentlist/',
    APIHelperRequestTypeUserTransactionHistory: '/api/v1/me/transaction/history',
    APIHelperRequestTypeSearchMasjid: '/api/v1/masjid/search',
    APIHelperRequestTypeListBookmarkedMasjid: '/api/v2/me/bookmark',
    APIHelperRequestTypeIqamaByMasjid: '/api/v1/iqama',
    APIHelperRequestTypeTransactionRefundRequest: '/api/v2/me/transaction/refund/request',
    APIHelperRequestTypeBookmarkList: '/api/v2/me/bookmark',
    APIHelperRequestTypeBookmarkCreate: '/api/v2/me/bookmark/create',
    APIHelperRequestTypeBookmarkRemove: '/api/v2/me/bookmark/delete',
    APIHelperRequestTypeContentViewer: '/api/v2/content/view',
    APIHelperRequestTypeContentProjectProgress: '/api/v2/content/project/progress',
    APIV2HelperRequestTypeSearchMasjid: '/api/v2/masjid/search',
    APIV2HelperRequestTypeStore: '/api/v2/product/list',
    APIV2HelperRequestTypeOrderPay: '/api/v2/order/pay',
    APIV2HelperRequestTypeOrderCreate: '/api/v2/order/create',
    APIV2HelperRequestTypeOrderHistory: '/api/v2/me/order/history',
};

//export default Global
